\"
\" lu.1: This is a manual page for 'lu' program. This file is part of the
\" lu <http://botao.org/> project.
\"

\" No hyphenation
.hy 0
.nr HY 0

.TH lu "1" "2014-04-15" "lu" "User Commands"
.SH NAME
\fBlu\fR - level usage

.SH SYNOPSIS
.TP 5
\fBlu\fR [\fBOPTIONS\fR] [{DIRECTORY|MOUNT-POINT}]

.SH DESCRIPTION
.PP

To get a list of commands specific to lu, use :
lu -h


.SH BUGS
Report bugs at:- http://botao.org/

.SH AUTHOR
Alexandre Botao
